### ISSUE TITLE
GRC?

### ISSUE THREAD

**Issue by gte620v** [ryanvolz/gnuradio-feedstock#1]
Thanks for contributing this to conda!  Is there a reason that GRC is disabled in the build.sh?  If I enable will it work?

**Comment by ryanvolz** [comment]
I'd certainly like to include it, but it's proving difficult for the moment. GRC needs pygtk, which is currently not packaged in conda-forge. I see now that gtk2 got added to conda-forge finally about a month ago, so maybe I can make it work now. Locally you might be able to do it as well.

**Comment by gte620v** [comment]
I've not messed with conda recipes, but i'll take a look. Thanks!
